# Use a imagem oficial do Grafana
FROM grafana/grafana:latest

# Defina a variável de ambiente para desabilitar o login anônimo
ENV GF_AUTH_ANONYMOUS_ENABLED=false

# Exponha a porta em que o Grafana estará escutando (a mesma definida em "ports" no docker-compose.yml)
EXPOSE 3000