global:
  scrape_interval: 5s
scrape_configs:
  - job_name: "backend-metrics"
    metrics_path: /api/metrics
    static_configs:
      - targets: ["host.docker.internal:8000"]
  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
      - targets:
        - cadvisor:8080