global:
  scrape_interval: 5s
scrape_configs:
  - job_name: "backend-metrics"
    metrics_path: /api/metrics
    static_configs:
      - targets: ["api.staging.quevende.com.br"]
  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
      - targets:
        - cadvisor:8080
  - job_name: 'blackbox'
    metrics_path: /probe
    static_configs:
      - targets:
        - empresa.staging.quevende.com.br # Target to probe with http on port 8080.
        - admin.staging.quevende.com.br
        - candidato.staging.quevende.com.br
        - api.staging.quevende.com.br/api/metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: host.docker.internal:9115